name: Docker Image CI

on:
  push:
    branches: 
      - '**'

jobs:
  build_docker:
    runs-on: self-hosted
    steps:
      - run: git clone -b $GITHUB_REF_NAME https://github.com/SystemsPurge/controller.git && cd controller && docker build --tag $CRU/$CRI:$GITHUB_REF_NAME . && cd .. && rm -rf controller

  deploy_docker:
    runs-on: self-hosted
    needs: [build_docker]
    steps:
      - run:  docker login -u $CRU -p $CRP && docker push $CRU/$CRI:$GITHUB_REF_NAME
